In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
#install pandas you will always need to import libary into my enviroment

In [ ]:
import pandas as pd

In [ ]:
#green tick means doen correctly then shrten to pd

creating data frame manually

In [ ]:
data= {"calories":[420 , 380, 390],
       "duration":[50,40,45]}
# this is a dictionary

In [ ]:
df = pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       380        40
2       390        45

In [ ]:
# load data into a dataframe # then add df= data frame # add print

In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

importing data set

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving student.xlsx to student.xlsx

In [ ]:
#pd.read_csv("student.csv") # if it has csv extension

In [ ]:
df = pd.read_excel("student.xlsx") # if it has xlsx extension

In [ ]:
# added df to save in the memeory
# you can selsect to read so many formats of dat ie json html sql etc.
#the goodness of pandas libary

In [ ]:
df

# call print df or just df

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78     NaN
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
# now insepct your data set
# which is always good pratice for any data set you get on any sofwher

In [ ]:
df.head() # top 5 rows with th head function

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
df.head(10) # specfied how many by adding 10 in the agurment

   id         name  class  mark  gender
0   1     John Deo   Four    75  female
1   2     Max Ruin  Three    85    male
2   3       Arnold  Three    55    male
3   4   Krish Star   Four    60  female
4   5    John Mike   Four    60  female
5   6    Alex John   Four    55    male
6   7  My John Rob  Fifth    78    male
7   8       Asruid   Five    85    male
8   9      Tes Qry    Six    78     NaN
9  10     Big John   Four    55  female

In [ ]:
df.tail() # shows the end 5

    id         name  class  mark  gender
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
df.tail(10) # brings back last ten

    id         name  class  mark  gender
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
df.count() # rows by colums

id        35
name      34
class     34
mark      35
gender    33
dtype: int64

In [ ]:
len (df)# rows count

35

In [ ]:
df.sample() # radonm sample data

    id    name  class  mark gender
25  26  Crelea  Seven    79   male

In [ ]:
df.sample(3)

    id       name  class  mark  gender
4    5  John Mike   Four    60  female
7    8     Asruid   Five    85    male
12  13        Kty  Seven    88  female

In [ ]:
df.shape # row , colums to understand exploring your data

(35, 5)

In [ ]:
df.info () # will show null data types etc count = excluding missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      35 non-null     int64
 1   name    34 non-null     object
 2   class   34 non-null     object
 3   mark    35 non-null     int64
 4   gender  33 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.5+ KB

In [ ]:
# name 1 missing value
# class 1 misisng value
# gender 2 missing values

In [ ]:
df.columns # useful if you need to rename

Index(['id', 'name', 'class', 'mark', 'gender'], dtype='object')

In [ ]:
df.describe() # satstistcal summary
# is std+standard deviation is greater than mean, there is a possible outlier

              id       mark
count  35.000000  35.000000
mean   18.000000  74.657143
std    10.246951  16.401117
min     1.000000  18.000000
25%     9.500000  62.500000
50%    18.000000  79.000000
75%    26.500000  88.000000
max    35.000000  96.000000

In [ ]:
df.size # 35*5 rows by colums

175

In [ ]:
df.dtypes# return the dta types

id         int64
name      object
class     object
mark       int64
gender    object
dtype: object

In [ ]:
df.isnull().sum()

# gives the null values counts
#missing values in eadch colums

id        0
name      1
class     1
mark      0
gender    2
dtype: int64

In [ ]:
df.duplicated().sum()
# counts the duplicated rows
# the sum counts it
# if not it will say true or false

0

subsetting a dataframe

In [ ]:
df["name"] #returning a single collum

0        John Deo
1        Max Ruin
2          Arnold
3      Krish Star
4       John Mike
5       Alex John
6     My John Rob
7          Asruid
8         Tes Qry
9        Big John
10         Ronald
11          Recky
12            Kty
13           Bigy
14       Tade Row
15          Gimmy
16          Tumyu
17          Honny
18          Tinny
19         Jackly
20     Babby John
21         Reggid
22          Herod
23      Tiddy Now
24       Giff Tow
25         Crelea
26            NaN
27      Rojj Base
28    Tess Played
29      Reppy Red
30    Marry Toeey
31      Binn Rott
32      Kenn Rein
33       Gain Toe
34     Rows Noump
Name: name, dtype: object

In [ ]:
# can also use
df.name # migth not work if you have a colum with the same name as a key word
      #so you can use the above , however you migth see like this to be aware.

0        John Deo
1        Max Ruin
2          Arnold
3      Krish Star
4       John Mike
5       Alex John
6     My John Rob
7          Asruid
8         Tes Qry
9        Big John
10         Ronald
11          Recky
12            Kty
13           Bigy
14       Tade Row
15          Gimmy
16          Tumyu
17          Honny
18          Tinny
19         Jackly
20     Babby John
21         Reggid
22          Herod
23      Tiddy Now
24       Giff Tow
25         Crelea
26            NaN
27      Rojj Base
28    Tess Played
29      Reppy Red
30    Marry Toeey
31      Binn Rott
32      Kenn Rein
33       Gain Toe
34     Rows Noump
Name: name, dtype: object

In [ ]:
# can ASLO apply this with differnet methods ie
df["class"].head()

0     Four
1    Three
2    Three
3     Four
4     Four
Name: class, dtype: object

In [ ]:
# another example using max
df['mark'].max()

96

In [ ]:
# can also use mutlipe colums using duble [[]]
df[["name","gender"]]

           name  gender
0      John Deo  female
1      Max Ruin    male
2        Arnold    male
3    Krish Star  female
4     John Mike  female
5     Alex John    male
6   My John Rob    male
7        Asruid    male
8       Tes Qry     NaN
9      Big John  female
10       Ronald  female
11        Recky  female
12          Kty  female
13         Bigy  female
14     Tade Row    male
15        Gimmy    male
16        Tumyu    male
17        Honny    male
18        Tinny    male
19       Jackly  female
20   Babby John  female
21       Reggid  female
22        Herod    male
23    Tiddy Now    male
24     Giff Tow    male
25       Crelea    male
26          NaN     NaN
27    Rojj Base  female
28  Tess Played    male
29    Reppy Red  female
30  Marry Toeey    male
31    Binn Rott  female
32    Kenn Rein  female
33     Gain Toe    male
34   Rows Noump  female

In [ ]:
df[["name","gender"]].sample (5) # again can use with other functions

          name  gender
33    Gain Toe    male
3   Krish Star  female
26         NaN     NaN
2       Arnold    male
31   Binn Rott  female

In [ ]:
# using indexes

In [ ]:
df[1:5] # start from row index 1 and return 4 rows

   id        name  class  mark  gender
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
df["name"][0:2] #row indexes [0:2] #[start:stop] stopping is not included unless you say

0    John Deo
1    Max Ruin
Name: name, dtype: object

Loc and iloc operators

In [ ]:
df.loc[0,'name']# first row and name column
# loc [rows & clums]

'John Deo'

In [ ]:
#return mark for krish
df.loc[3,'mark']

60

In [ ]:
df.loc[3, ["name", "mark"]] #row three and a list

name    Krish Star
mark            60
Name: 3, dtype: object

In [ ]:
#df.loc[3.'name', 'mark'] #this will return error as it has to be in
# a list
df.loc[0:3,['name','mark'] ] #with the range included ,loc includes the stopping point

         name  mark
0    John Deo    75
1    Max Ruin    85
2      Arnold    55
3  Krish Star    60

In [ ]:
# if you want to include the rows and colums use iloc
df.iloc[3,3] #iloc[rows,colums]

60

In [ ]:
df.iloc[0:3, [1,2]]
 # iloc you provide the index of the colums #
 # doesnt include the stopping point like loc see we put [0:3]
 #and it stopped at 2

       name  class
0  John Deo   Four
1  Max Ruin  Three
2    Arnold  Three

In [ ]:
df.iloc[1:3 , 1] # for row range stropping point (index 3) will not be in the output
                 # rows must come first

1    Max Ruin
2      Arnold
Name: name, dtype: object

In [ ]:
df.iloc[1:3 , [1,4]] #if you want more colums you need to out them in a list

       name gender
1  Max Ruin   male
2    Arnold   male

In [ ]:
# What is the index for gender column ?
df.columns.get_loc("gender")

4

In [ ]:
df.iloc[1:3 , [1, df.columns.get_loc("gender")]] # for row range stropping point (index 3) will not be in the output

       name gender
1  Max Ruin   male
2    Arnold   male

In [ ]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

# **Flitering**

In [ ]:
# student mark greater than 50
df["mark"] #this will return the collum

0     75
1     85
2     55
3     60
4     60
5     55
6     78
7     85
8     78
9     55
10    89
11    94
12    88
13    88
14    88
15    88
16    54
17    75
18    18
19    65
20    69
21    55
22    79
23    78
24    88
25    79
26    81
27    86
28    55
29    79
30    88
31    90
32    96
33    69
34    88
Name: mark, dtype: int64

In [ ]:
df["mark"] >50 # will give me a true or false as it compares the results
               #to if the mark is >50 or not

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18    False
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
Name: mark, dtype: bool

In [ ]:
# so i use df in the bracken to fliter the roles
#when its placed in a subsetting it will return the results i need.
df[df["mark"] >50]

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78     NaN
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
df[df["mark"]>=90]

    id       name  class  mark  gender
11  12      Recky    Six    94  female
31  32  Binn Rott  Seven    90  female
32  33  Kenn Rein    Six    96  female

In [ ]:
df.loc[df["mark"]>90,:] # loc [rows,column] : means all range of columns

    id       name class  mark  gender
11  12      Recky   Six    94  female
32  33  Kenn Rein   Six    96  female

In [ ]:
df.loc[df["mark"]>90,"name"] # see i put the collmun name and how it differs?

11        Recky
32    Kenn Rein
Name: name, dtype: object

In [ ]:
# return info about female students

In [ ]:
df[df["gender"]=="female"] # == mean comprasion ie this = this

    id        name  class  mark  gender
0    1    John Deo   Four    75  female
3    4  Krish Star   Four    60  female
4    5   John Mike   Four    60  female
9   10    Big John   Four    55  female
10  11      Ronald    Six    89  female
11  12       Recky    Six    94  female
12  13         Kty  Seven    88  female
13  14        Bigy  Seven    88  female
19  20      Jackly   Nine    65  female
20  21  Babby John   Four    69  female
21  22      Reggid  Seven    55  female
27  28   Rojj Base  Seven    86  female
29  30   Reppy Red    Six    79  female
31  32   Binn Rott  Seven    90  female
32  33   Kenn Rein    Six    96  female
34  35  Rows Noump    Six    88  female

write a code to selct all rows where the 'class is 'four'

In [ ]:
# prompt: write a code to select all rows where the 'class is 'four'

df[df["class"] == "Four"]

    id         name class  mark  gender
0    1     John Deo  Four    75  female
3    4   Krish Star  Four    60  female
4    5    John Mike  Four    60  female
5    6    Alex John  Four    55    male
9   10     Big John  Four    55  female
15  16        Gimmy  Four    88    male
20  21   Babby John  Four    69  female
30  31  Marry Toeey  Four    88    male

In [ ]:
df[df["class"]=='Four'] # check for captials

    id         name class  mark  gender
0    1     John Deo  Four    75  female
3    4   Krish Star  Four    60  female
4    5    John Mike  Four    60  female
5    6    Alex John  Four    55    male
9   10     Big John  Four    55  female
15  16        Gimmy  Four    88    male
20  21   Babby John  Four    69  female
30  31  Marry Toeey  Four    88    male

In [ ]:
# return info about female students using loc

In [ ]:
df.loc[df["gender"]=='female'].head (10)

    id        name  class  mark  gender
0    1    John Deo   Four    75  female
3    4  Krish Star   Four    60  female
4    5   John Mike   Four    60  female
9   10    Big John   Four    55  female
10  11      Ronald    Six    89  female
11  12       Recky    Six    94  female
12  13         Kty  Seven    88  female
13  14        Bigy  Seven    88  female
19  20      Jackly   Nine    65  female
20  21  Babby John   Four    69  female

In [ ]:
df.loc[df["gender"] == "female", df.columns[0:3]].head()

    id        name class
0    1    John Deo  Four
3    4  Krish Star  Four
4    5   John Mike  Four
9   10    Big John  Four
10  11      Ronald   Six

In [ ]:
# return info about female students name, class and gender onlys
df.loc[df["gender"]=="Female",["name", "gender", "class"]]
# this didnt work beacuse the captial F in female

Empty DataFrame
Columns: [name, gender, class]
Index: []

In [ ]:
df.loc[df["gender"]=="female", ["name", "class", "gender"]]

          name  class  gender
0     John Deo   Four  female
3   Krish Star   Four  female
4    John Mike   Four  female
9     Big John   Four  female
10      Ronald    Six  female
11       Recky    Six  female
12         Kty  Seven  female
13        Bigy  Seven  female
19      Jackly   Nine  female
20  Babby John   Four  female
21      Reggid  Seven  female
27   Rojj Base  Seven  female
29   Reppy Red    Six  female
31   Binn Rott  Seven  female
32   Kenn Rein    Six  female
34  Rows Noump    Six  female

In [ ]:
df[df["gender"]=="female"][["name","class", "gender"]] # another way to appraoch it

          name  class  gender
0     John Deo   Four  female
3   Krish Star   Four  female
4    John Mike   Four  female
9     Big John   Four  female
10      Ronald    Six  female
11       Recky    Six  female
12         Kty  Seven  female
13        Bigy  Seven  female
19      Jackly   Nine  female
20  Babby John   Four  female
21      Reggid  Seven  female
27   Rojj Base  Seven  female
29   Reppy Red    Six  female
31   Binn Rott  Seven  female
32   Kenn Rein    Six  female
34  Rows Noump    Six  female

In [ ]:
# return info about six class female student
df[(df["gender"]=="female") & (df["class"]=="Six")]
# the conditions ar spilt in round() brackets

    id        name class  mark  gender
10  11      Ronald   Six    89  female
11  12       Recky   Six    94  female
29  30   Reppy Red   Six    79  female
32  33   Kenn Rein   Six    96  female
34  35  Rows Noump   Six    88  female

In [ ]:
# return name, class, gender about six class female student
df[(df["gender"]=="female") & (df["class"]=="Six")][["name", "class", "gender"]]
# this allows you to then select the names of the collums you want by adding them after

          name class  gender
10      Ronald   Six  female
11       Recky   Six  female
29   Reppy Red   Six  female
32   Kenn Rein   Six  female
34  Rows Noump   Six  female

In [ ]:
# return name, class, gender about six class female student
df.loc[(df["gender"]=="female") & (df["class"]=="Six"), ["name", "class", "gender"]]

          name class  gender
10      Ronald   Six  female
11       Recky   Six  female
29   Reppy Red   Six  female
32   Kenn Rein   Six  female
34  Rows Noump   Six  female

In [ ]:
# this works too with the , ["name", "class", "gender"]] or
#six )][["name", "class", "gender"]] at the end

In [ ]:
#Average mark across all students

#Average mark across all students

Write Python code to calculate



Average mark across all students

Average mark across male and female students

Max and min mark

Max mark for male and female students

Average mark for class 'Five'

Average mark for class 'Six' and male students only

In [ ]:
df["mark"].mean()

74.65714285714286

In [ ]:
df.loc[:, "mark"].mean()

74.65714285714286

In [ ]:
#Average mark across male and female students
# steps
# filter by gender
# select mark colum
# apply avergae

df.loc[df["gender"]=="male", "mark"].mean()

71.58823529411765

In [ ]:
df.loc[df["gender"]=="female", "mark"].mean()

77.3125

In [ ]:
df.groupby("gender")["mark"].mean()

gender
female    77.312500
male      71.588235
Name: mark, dtype: float64

Max and min mark

In [ ]:
df.loc[:, "mark"].max()

96

In [ ]:
df.loc[:, "mark"].min()

18

In [ ]:
# filter by gender
# select mark column
# apply max
# th [df[gender] add the condition to this.
df.loc[df["gender"]=="male", "mark"].max()

88

In [ ]:
#Average mark for class 'Five'

df.loc[df["class"]=="Five", "mark"].mean()

80.0

In [ ]:
#Average mark for class 'Six' and male students only
# filter by class six
#filter by gender male
#acess mark colum calaculate avergae.
df.loc[(df["class"]=="Six") & (df["gender"]=="male"), "mark"].mean()
# the two brackets have to divide the 2 conditons

54.0

In [ ]:
df[(df["gender"]=="male") & (df["class"]=="Six")]["mark"].mean()

54.0

In [ ]:
# find the student who has mark 18
df.loc[df["mark"]==18]

    id   name class  mark gender
18  19  Tinny  Nine    18   male

In [ ]:
df[df["mark"]==18] # also works

    id   name class  mark gender
18  19  Tinny  Nine    18   male

In [ ]:
df.loc[df["mark"]==df['mark'].min()] # the min mark

    id   name class  mark gender
18  19  Tinny  Nine    18   male

In [ ]:
# just an attempt
df[(df["gender"]=="female") & (df["mark"] > df["mark"].mean())]

    id        name  class  mark  gender
0    1    John Deo   Four    75  female
10  11      Ronald    Six    89  female
11  12       Recky    Six    94  female
12  13         Kty  Seven    88  female
13  14        Bigy  Seven    88  female
27  28   Rojj Base  Seven    86  female
29  30   Reppy Red    Six    79  female
31  32   Binn Rott  Seven    90  female
32  33   Kenn Rein    Six    96  female
34  35  Rows Noump    Six    88  female

SORTING RESULTS

In [ ]:
# Sorting by names
df.loc[:,:].sort_values(by="name")

    id         name  class  mark  gender
5    6    Alex John   Four    55    male
2    3       Arnold  Three    55    male
7    8       Asruid   Five    85    male
20  21   Babby John   Four    69  female
9   10     Big John   Four    55  female
13  14         Bigy  Seven    88  female
31  32    Binn Rott  Seven    90  female
25  26       Crelea  Seven    79    male
33  34     Gain Toe  Seven    69    male
24  25     Giff Tow  Seven    88    male
15  16        Gimmy   Four    88    male
22  23        Herod  Eight    79    male
17  18        Honny   Five    75    male
19  20       Jackly   Nine    65  female
0    1     John Deo   Four    75  female
4    5    John Mike   Four    60  female
32  33    Kenn Rein    Six    96  female
3    4   Krish Star   Four    60  female
12  13          Kty  Seven    88  female
30  31  Marry Toeey   Four    88    male
1    2     Max Ruin  Three    85    male
6    7  My John Rob  Fifth    78    male
11  12        Recky    Six    94  female
21  22       Reggid  Seven    55  female
29  30    Reppy Red    Six    79  female
27  28    Rojj Base  Seven    86  female
10  11       Ronald    Six    89  female
34  35   Rows Noump    Six    88  female
14  15     Tade Row    NaN    88    male
8    9      Tes Qry    Six    78     NaN
28  29  Tess Played  Seven    55    male
23  24    Tiddy Now  Seven    78    male
18  19        Tinny   Nine    18    male
16  17        Tumyu    Six    54    male
26  27          NaN  Three    81     NaN

In [ ]:
df.sort_values(by="name")

    id         name  class  mark  gender
5    6    Alex John   Four    55    male
2    3       Arnold  Three    55    male
7    8       Asruid   Five    85    male
20  21   Babby John   Four    69  female
9   10     Big John   Four    55  female
13  14         Bigy  Seven    88  female
31  32    Binn Rott  Seven    90  female
25  26       Crelea  Seven    79    male
33  34     Gain Toe  Seven    69    male
24  25     Giff Tow  Seven    88    male
15  16        Gimmy   Four    88    male
22  23        Herod  Eight    79    male
17  18        Honny   Five    75    male
19  20       Jackly   Nine    65  female
0    1     John Deo   Four    75  female
4    5    John Mike   Four    60  female
32  33    Kenn Rein    Six    96  female
3    4   Krish Star   Four    60  female
12  13          Kty  Seven    88  female
30  31  Marry Toeey   Four    88    male
1    2     Max Ruin  Three    85    male
6    7  My John Rob  Fifth    78    male
11  12        Recky    Six    94  female
21  22       Reggid  Seven    55  female
29  30    Reppy Red    Six    79  female
27  28    Rojj Base  Seven    86  female
10  11       Ronald    Six    89  female
34  35   Rows Noump    Six    88  female
14  15     Tade Row    NaN    88    male
8    9      Tes Qry    Six    78     NaN
28  29  Tess Played  Seven    55    male
23  24    Tiddy Now  Seven    78    male
18  19        Tinny   Nine    18    male
16  17        Tumyu    Six    54    male
26  27          NaN  Three    81     NaN

In [ ]:
df.sort_values(by="mark")

    id         name  class  mark  gender
18  19        Tinny   Nine    18    male
16  17        Tumyu    Six    54    male
28  29  Tess Played  Seven    55    male
2    3       Arnold  Three    55    male
5    6    Alex John   Four    55    male
21  22       Reggid  Seven    55  female
9   10     Big John   Four    55  female
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
33  34     Gain Toe  Seven    69    male
0    1     John Deo   Four    75  female
17  18        Honny   Five    75    male
8    9      Tes Qry    Six    78     NaN
6    7  My John Rob  Fifth    78    male
23  24    Tiddy Now  Seven    78    male
29  30    Reppy Red    Six    79  female
22  23        Herod  Eight    79    male
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
1    2     Max Ruin  Three    85    male
7    8       Asruid   Five    85    male
27  28    Rojj Base  Seven    86  female
14  15     Tade Row    NaN    88    male
30  31  Marry Toeey   Four    88    male
24  25     Giff Tow  Seven    88    male
12  13          Kty  Seven    88  female
15  16        Gimmy   Four    88    male
13  14         Bigy  Seven    88  female
34  35   Rows Noump    Six    88  female
10  11       Ronald    Six    89  female
31  32    Binn Rott  Seven    90  female
11  12        Recky    Six    94  female
32  33    Kenn Rein    Six    96  female

In [ ]:
#how to sort in desc order

In [ ]:
df.sort_values(by="mark", ascending=False)

    id         name  class  mark  gender
32  33    Kenn Rein    Six    96  female
11  12        Recky    Six    94  female
31  32    Binn Rott  Seven    90  female
10  11       Ronald    Six    89  female
24  25     Giff Tow  Seven    88    male
15  16        Gimmy   Four    88    male
14  15     Tade Row    NaN    88    male
13  14         Bigy  Seven    88  female
12  13          Kty  Seven    88  female
34  35   Rows Noump    Six    88  female
30  31  Marry Toeey   Four    88    male
27  28    Rojj Base  Seven    86  female
7    8       Asruid   Five    85    male
1    2     Max Ruin  Three    85    male
26  27          NaN  Three    81     NaN
22  23        Herod  Eight    79    male
29  30    Reppy Red    Six    79  female
25  26       Crelea  Seven    79    male
8    9      Tes Qry    Six    78     NaN
6    7  My John Rob  Fifth    78    male
23  24    Tiddy Now  Seven    78    male
0    1     John Deo   Four    75  female
17  18        Honny   Five    75    male
20  21   Babby John   Four    69  female
33  34     Gain Toe  Seven    69    male
19  20       Jackly   Nine    65  female
4    5    John Mike   Four    60  female
3    4   Krish Star   Four    60  female
21  22       Reggid  Seven    55  female
9   10     Big John   Four    55  female
28  29  Tess Played  Seven    55    male
5    6    Alex John   Four    55    male
2    3       Arnold  Three    55    male
16  17        Tumyu    Six    54    male
18  19        Tinny   Nine    18    male

In [ ]:
df.sort_values(by="mark", ascending=False).head(10)

    id        name  class  mark  gender
32  33   Kenn Rein    Six    96  female
11  12       Recky    Six    94  female
31  32   Binn Rott  Seven    90  female
10  11      Ronald    Six    89  female
24  25    Giff Tow  Seven    88    male
15  16       Gimmy   Four    88    male
14  15    Tade Row    NaN    88    male
13  14        Bigy  Seven    88  female
12  13         Kty  Seven    88  female
34  35  Rows Noump    Six    88  female

In [ ]:
#find the student with the highest mark
df.sort_values(by="mark", ascending=False).head(1)

    id       name class  mark  gender
32  33  Kenn Rein   Six    96  female

In [ ]:

# return student who are female or at class seven
#| the pipeline is the or
#use the () () within the [] to slect the mutilpe conditions
#then but the order by . kdnbcsdkv at the end
df[(df["gender"]=="female") | (df["class"]=="Seven")].sort_values(by="mark")

    id         name  class  mark  gender
21  22       Reggid  Seven    55  female
9   10     Big John   Four    55  female
28  29  Tess Played  Seven    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
19  20       Jackly   Nine    65  female
33  34     Gain Toe  Seven    69    male
20  21   Babby John   Four    69  female
0    1     John Deo   Four    75  female
23  24    Tiddy Now  Seven    78    male
25  26       Crelea  Seven    79    male
29  30    Reppy Red    Six    79  female
27  28    Rojj Base  Seven    86  female
12  13          Kty  Seven    88  female
24  25     Giff Tow  Seven    88    male
13  14         Bigy  Seven    88  female
34  35   Rows Noump    Six    88  female
10  11       Ronald    Six    89  female
31  32    Binn Rott  Seven    90  female
11  12        Recky    Six    94  female
32  33    Kenn Rein    Six    96  female

VALUE_COUNTS ()

In [ ]:
df['gender'].unique() # will show you how many variables
# nan means null value

array(['female', 'male', nan], dtype=object)

In [ ]:
df.isnull().sum()
 # how many missing values

id        0
name      1
class     1
mark      0
gender    2
dtype: int64

In [ ]:
# how many male and females ar there ?
df["gender"].value_counts()

gender
male      17
female    16
Name: count, dtype: int64

In [ ]:
# number of class and students
df["class"].value_counts()

class
Seven    10
Four      8
Six       7
Three     3
Five      2
Nine      2
Fifth     1
Eight     1
Name: count, dtype: int64

In [ ]:
#write  the code to add a new column "passed "
#that indicates whether the student passed (mark.=60)

In [ ]:
# prompt: #write  the code to add a new column "passed "
# #that indicates whether the student passed (mark.=60)

df['passed'] = df['mark'] >= 60

In [ ]:
df.head()

   id        name  class  mark  gender  passed
0   1    John Deo   Four    75  female    True
1   2    Max Ruin  Three    85    male    True
2   3      Arnold  Three    55    male   False
3   4  Krish Star   Four    60  female    True
4   5   John Mike   Four    60  female    True

In [ ]:
# prompt: write a code to rename the mark column to score

import pandas as pd

# Assuming your DataFrame is named 'df' and already loaded

df = df.rename(columns={'mark': 'score'})
print(df.head())

   id        name  class  score  gender  passed
0   1    John Deo   Four     75  female    True
1   2    Max Ruin  Three     85    male    True
2   3      Arnold  Three     55    male   False
3   4  Krish Star   Four     60  female    True
4   5   John Mike   Four     60  female    True

In [ ]:
# prompt: write a code to drop the pass column

# Assuming your DataFrame is named 'df' and already loaded
df = df.drop('passed', axis=1)
print(df.head())

   id        name  class  score  gender
0   1    John Deo   Four     75  female
1   2    Max Ruin  Three     85    male
2   3      Arnold  Three     55    male
3   4  Krish Star   Four     60  female
4   5   John Mike   Four     60  female